1. **Title**

Day 9 - Processed E-commerce Dataset

This notebook combines Orders, Customers, and Products datasets using Pandas and creates a clean processed dataset.

2. **Import Pandas**

In [2]:
import pandas as pd

3. **Load the datasets**

In [3]:
orders = pd.read_csv("Day9_Orders.csv")
customers = pd.read_csv("Day9_Customers.csv")
products = pd.read_csv("Day9_Products.csv")

print("Orders:", orders.shape)
print("Customers:", customers.shape)
print("Products:", products.shape)

Orders: (120, 7)
Customers: (30, 5)
Products: (20, 5)

4. **View the datasets**

In [4]:
orders.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

In [5]:
customers.head()

  Customer_ID Customer_Name      City Region Membership_Type
0        C001  Aarav Sharma  Srinagar  North         Premium
1        C002     Zoya Khan     Delhi  North         Regular
2        C003   Rohan Mehta    Mumbai   West         Premium
3        C004  Ananya Singh     Jammu  North         Regular
4        C005     Kabir Ali   Lucknow  North             New

In [6]:
products.head()

  Product_ID         Product_Name     Category  Unit_Price     Brand
0       P001  Wireless Headphones  Electronics        1499  SoundMax
1       P002  Mechanical Keyboard  Electronics        2499    KeyPro
2       P003       Wireless Mouse  Electronics         899  TechGear
3       P004          Smart Watch  Electronics        3299   FitTech
4       P005           Power Bank  Electronics        1199  VoltPlus

5. **Merge Orders and Customers**

In [7]:
data = pd.merge(orders, customers, on="Customer_ID")
data.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New

6. **Merge with Products**

In [8]:
data = pd.merge(data, products, on="Product_ID")
data.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew

7. **Demonstrate concat()**

In [9]:
sample1 = orders.head(3)
sample2 = orders.tail(3)
combined = pd.concat([sample1, sample2])
combined

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
117,O0118,2026-03-09,C025,P016,4,Credit Card,Delivered
118,O0119,2026-02-03,C015,P019,2,Debit Card,Delivered
119,O0120,2026-01-21,C013,P020,1,Cash on Delivery,Cancelled

8. **DateTime Operations**

In [11]:
data["Order_Date"] = pd.to_datetime(data["Order_Date"])
data["Month"] = data["Order_Date"].dt.month
data["Day"] = data["Order_Date"].dt.day
data["Day_of_Week"] = data["Order_Date"].dt.day_name()

data[["Order_Date", "Month", "Day", "Day_of_Week"]].head()

  Order_Date  Month  Day Day_of_Week
0 2026-02-19      2   19    Thursday
1 2026-01-25      1   25      Sunday
2 2026-02-26      2   26    Thursday
3 2026-03-04      3    4   Wednesday
4 2026-03-29      3   29      Sunday

9. **Use apply() to create a useful column**

In [12]:
data["Total_Amount"] = data.apply(
    lambda row: row["Quantity"] * row["Unit_Price"], axis=1
)

data.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand,Month,Day,Day_of_Week,Total_Amount
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro,2,19,Thursday,4998
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear,1,25,Sunday,1798
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech,2,26,Thursday,3299
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress,3,4,Wednesday,2997
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew,3,29,Sunday,17495

10. **Organize the final DataFrame**

In [13]:
final_data = data[
    [
        "Order_ID",
        "Order_Date",
        "Month",
        "Day",
        "Day_of_Week",
        "Customer_ID",
        "Customer_Name",
        "City",
        "Region",
        "Membership_Type",
        "Product_ID",
        "Product_Name",
        "Category",
        "Brand",
        "Quantity",
        "Unit_Price",
        "Total_Amount",
        "Payment_Method",
        "Order_Status"
    ]
]

final_data.head()

,Order_ID,Order_Date,Month,Day,Day_of_Week,Customer_ID,Customer_Name,City,Region,Membership_Type,Product_ID,Product_Name,Category,Brand,Quantity,Unit_Price,Total_Amount,Payment_Method,Order_Status
0,O0001,2026-02-19,2,19,Thursday,C027,Harsh Vardhan,Noida,North,Premium,P019,Cricket Bat,Sports,BatPro,2,2499,4998,Credit Card,Delivered
1,O0002,2026-01-25,1,25,Sunday,C006,Ishita Gupta,Bengaluru,South,Premium,P003,Wireless Mouse,Electronics,TechGear,2,899,1798,Debit Card,Delivered
2,O0003,2026-02-26,2,26,Thursday,C015,Karan Joshi,Chandigarh,North,Regular,P004,Smart Watch,Electronics,FitTech,1,3299,3299,Cash on Delivery,Delivered
3,O0004,2026-03-04,3,4,Wednesday,C024,Maryam Khan,Hyderabad,South,Regular,P015,Machine Learning Basics,Books,AIPress,3,999,2997,Net Banking,Delivered
4,O0005,2026-03-29,3,29,Sunday,C025,Reyansh Jain,Kolkata,East,New,P009,Coffee Maker,Home & Kitchen,HomeBrew,5,3499,17495,Credit Card,Delivered

11. **Check the processed dataset**

In [14]:
print("Rows:", final_data.shape[0])
print("Columns:", final_data.shape[1])
final_data.info()

Rows: 120
Columns: 19
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         120 non-null    object
 1   Order_Date       120 non-null    datetime64[ns]
 2   Month            120 non-null    int32
 3   Day              120 non-null    int32
 4   Day_of_Week      120 non-null    object
 5   Customer_ID      120 non-null    object
 6   Customer_Name    120 non-null    object
 7   City             120 non-null    object
 8   Region           120 non-null    object
 9   Membership_Type  120 non-null    object
 10  Product_ID       120 non-null    object
 11  Product_Name     120 non-null    object
 12  Category         120 non-null    object
 13  Brand            120 non-null    object
 14  Quantity         120 non-null    int64
 15  Unit_Price       120 non-null    int64
 16  Total_Amount     120 non-null    int64
 17  Payment_Method   120 non-null    object
 18  Order_Status     120 non-null    object
dtypes: datetime64[ns](1), int32(2), int64(3), object(13)
memory usage: 17.0+ KB

12. **Export as CSV**

In [15]:
final_data.to_csv("processed_ecommerce_dataset.csv", index=False)
print("Processed dataset saved successfully!")

Processed dataset saved successfully!

13. **Download it from Colab**

In [16]:
from google.colab import files
files.download("processed_ecommerce_dataset.csv")