1. **Title**

Day 11 - Cleaned Company Employee Dataset

This notebook identifies and fixes missing values, inconsistent entries, incorrect data types, and duplicate records using Pandas.

2. **Import Pandas**

In [1]:
import pandas as pd

3. **Load the Dataset**

In [2]:
df = pd.read_csv("Day11_Messy_Company_Employee_Dataset.csv")
df.head()

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,NaN,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

4. **Check the Dataset Before Cleaning**

In [3]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 157
Columns: 12

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        157 non-null    object
 1   Employee_Name      157 non-null    object
 2   Department         152 non-null    object
 3   Job_Title          157 non-null    object
 4   Age                153 non-null    float64
 5   Gender             152 non-null    object
 6   Annual_Salary      152 non-null    float64
 7   Experience_Years   154 non-null    float64
 8   Joining_Date       157 non-null    object
 9   City               152 non-null    object
 10  Performance_Score  154 non-null    float64
 11  Work_Mode          155 non-null    object
dtypes: float64(4), object(8)
memory usage: 14.8+ KB

In [5]:
df.isnull().sum()

Employee_ID          0
Employee_Name        0
Department           5
Job_Title            0
Age                  4
Gender               5
Annual_Salary        5
Experience_Years     3
Joining_Date         0
City                 5
Performance_Score    3
Work_Mode            2
dtype: int64

In [6]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 7

5. **Fix Inconsistent Text Entries**

In [9]:
text_columns = ["Department", "Gender", "City", "Work_Mode"]
for column in text_columns:
    df[column] = df[column].str.strip().str.title()

print(df["Department"].unique())
print(df["Gender"].unique())
print(df["City"].unique())
print(df["Work_Mode"].unique())

[nan 'Marketing' 'Human Resources' 'Engineering' 'Sales' 'Finance'
 'Data & Analytics' 'Customer Success' 'Operations']
['Other' 'Female' 'Male' nan]
['Pune' 'Mumbai' 'Bengaluru' 'Jaipur' 'Hyderabad' 'Chennai' 'Chandigarh'
 'Srinagar' 'Kolkata' 'Delhi' nan]
['Office' 'Remote' 'Hybrid' nan]

6. **Handle Missing Values**

In [10]:
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Annual_Salary"] = df["Annual_Salary"].fillna(df["Annual_Salary"].median())
df["Experience_Years"] = df["Experience_Years"].fillna(df["Experience_Years"].median())
df["Performance_Score"] = df["Performance_Score"].fillna(df["Performance_Score"].median())

In [11]:
df["Department"] = df["Department"].fillna(df["Department"].mode()[0])
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])
df["City"] = df["City"].fillna(df["City"].mode()[0])
df["Work_Mode"] = df["Work_Mode"].fillna(df["Work_Mode"].mode()[0])

7. **Convert Date Column**

In [13]:
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])
print(df.dtypes)

Employee_ID                  object
Employee_Name                object
Department                   object
Job_Title                    object
Age                         float64
Gender                       object
Annual_Salary               float64
Experience_Years            float64
Joining_Date         datetime64[ns]
City                         object
Performance_Score           float64
Work_Mode                    object
dtype: object

8. **Remove Duplicate Records**

In [15]:
df = df.drop_duplicates()
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

9. **Check the Dataset After Cleaning**

In [16]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 150
Columns: 12

In [17]:
print(df.isnull().sum())

Employee_ID          0
Employee_Name        0
Department           0
Job_Title            0
Age                  0
Gender               0
Annual_Salary        0
Experience_Years     0
Joining_Date         0
City                 0
Performance_Score    0
Work_Mode            0
dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 0 to 155
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        150 non-null    object
 1   Employee_Name      150 non-null    object
 2   Department         150 non-null    object
 3   Job_Title          150 non-null    object
 4   Age                150 non-null    float64
 5   Gender             150 non-null    object
 6   Annual_Salary      150 non-null    float64
 7   Experience_Years   150 non-null    float64
 8   Joining_Date       150 non-null    datetime64[ns]
 9   City               150 non-null    object
 10  Performance_Score  150 non-null    float64
 11  Work_Mode          150 non-null    object
dtypes: datetime64[ns](1), float64(4), object(7)
memory usage: 15.2+ KB

10. **Before vs After Comparison**

In [19]:
print("Before Cleaning")
print("Rows:", 157)
print("Duplicate Rows:", 7)

print("\nAfter Cleaning")
print("Rows:", df.shape[0])
print("Duplicate Rows:", df.duplicated().sum())
print("Missing Values:", df.isnull().sum().sum())

Before Cleaning
Rows: 157
Duplicate Rows: 7

After Cleaning
Rows: 150
Duplicate Rows: 0
Missing Values: 0

11. **View Cleaned Dataset**

In [20]:
df.head(10)

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Engineering,Data Scientist,48.0,Other,108371.0,13.20,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.10,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.20,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,9.35,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.90,2018-07-24,Hyderabad,4.0,Hybrid
5,EMP0117,Zoya Kapoor,Finance,Finance Manager,42.0,Male,128567.0,15.40,2017-08-02,Chennai,4.0,Hybrid
6,EMP0081,Maryam Mir,Marketing,Content Strategist,37.0,Male,58878.0,1.80,2024-01-18,Pune,2.0,Office
7,EMP0026,Omar Das,Engineering,QA Engineer,38.0,Male,112276.0,12.00,2019-05-14,Chandigarh,4.0,Hybrid
8,EMP0129,Dev Ahmed,Data & Analytics,Data Scientist,45.0,Male,135730.0,14.10,2021-01-27,Srinagar,2.0,Remote
9,EMP0121,Karan Patel,Data & Analytics,BI Analyst,40.0,Female,101886.0,8.50,2020-06-28,Chennai,4.0,Remote

12. **Export the Cleaned Dataset**

In [21]:
df.to_csv("cleaned_company_employee_dataset.csv", index=False)
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [22]:
from google.colab import files
files.download("cleaned_company_employee_dataset.csv")